apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - <DNSNAMEHERE>.eastus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - <DNSNAMEHERE>.eastus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-aks
    kind: ClusterIssuer