apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: hackfest
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
