kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: default-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "serviceaccounts", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: khaksrbac-viewdefault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "aksuser@<AZUREAD-DOMAIN>.onmicrosoft.com"
